fix: pass location info to header component
twreporter/twreporter-react pull request #2296
Opened 2022-11-07 03:21 UTC by Aylie-Chou

- `/* eslint-disable react/display-name */` setting is to resolve eslint error of `component definition is missing display name`.
  - [ref](https://bobbyhadz.com/blog/react-component-is-missing-display-name#:~:text=Set%20the%20displayName%20property%20on,line%20react%2Fdisplay%2Dname%20.)

2022-11-18 04:03 UTC, duidae requested changes

2022-11-21 08:25 UTC, Aylie-Chou commented on src/app.js
> +  releaseBranch: PropTypes.oneOf([
`BRANCH_PROP_TYPES` constant is added currently, I'd like to unify the declaration of releaseBranch prop type as `releaseBranch: BRANCH_PROP_TYPES` gradually. ([92568b1](https://github.com/twreporter/twreporter-react/pull/2296/commits/92568b170f9cd5fd583eaf1db906184f7e2ff2b8))

2022-11-21 08:26 UTC, Aylie-Chou commented on src/containers/app-shell.js
> +          {/* <WebPush apiOrigin={apiOrigin} userId={userId} /> */}
removed. ([92568b1](https://github.com/twreporter/twreporter-react/pull/2296/commits/92568b170f9cd5fd583eaf1db906184f7e2ff2b8))
ps. the comment code is refer to #2066

2022-11-24 02:27 UTC, duidae approved these changes

2022-11-24 03:26 UTC, merged