Feature/post tracking UI
twreporter/twreporter-react pull request #2870
Opened 2024-05-21 06:43 UTC by liruchen32

# Issue
[[會員制]重要報導追蹤-UI/前端: 我的閱讀頁](https://app.asana.com/0/1203699264568808/1207297044447667/f)

# Notice

# Dependency

2024-05-27 08:33 UTC, Aylie-Chou commented on src/components/my-reading/article-tracking-card.js
> +        <Rectangle $width={'100%'} $height={'16px'} $marginBottom="wide" />
Could we add a `enum` to manage $marginBottom type 🙏

2024-05-27 08:37 UTC, Aylie-Chou commented on src/components/my-reading/article-tracking-section.js
> +  | <left icon 24px> | <gap 16px> | <cards...> | <gap 16px> | <right icon 24px> |
good use of comments 👍

2024-05-28 03:32 UTC, Aylie-Chou commented on src/components/my-reading/article-tracking-section.js
> +                iconComponent={<Arrow direction={Arrow.Direction.RIGHT} />}
releaseBranch ?

2024-05-28 03:32 UTC, Aylie-Chou commented on src/components/my-reading/article-tracking-section.js
> +                iconComponent={<Arrow direction={Arrow.Direction.LEFT} />}
releaseBranch !

2024-05-28 03:33 UTC, Aylie-Chou requested changes
Mostly looking good~~
Please have a look at comments

2024-05-28 06:37 UTC, liruchen32 commented on src/components/my-reading/article-tracking-card.js
> +  trackingArticleTitle,
fixed

2024-05-28 06:43 UTC, liruchen32 commented on src/components/my-reading/article-tracking-section.js
> +                iconComponent={<Arrow direction={Arrow.Direction.RIGHT} />}
fixed

2024-05-28 06:43 UTC, liruchen32 commented on src/components/my-reading/article-tracking-section.js
> +                iconComponent={<Arrow direction={Arrow.Direction.LEFT} />}
fixed

2024-05-28 07:46 UTC, Aylie-Chou approved these changes
LGTM

2024-05-28 08:35 UTC, merged